### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by maktoobgar** [RyanNorooz/Windows-WifiPassword-Extractor#1]
# This is not a bug report
Just wanted to say some suggestions about __your code__ and some other about the __language__ you are using for hack stuff.
## Suggestion 1
Hacker guy needs to run the script in __Python__ in target machine, right?
This is not good, because what if the target machine __does not have__ python installed?
This script can be so much better if you generate an executable file(.exe) from it that just runs with a double click and does not open up a terminal windows and does all of the works invisible and unrecognizable.
## Suggestion 2
You are using python...
I'm not saying python is not gonna work in hack stuff, actually it works but the problem is the speed.
Yes, the speed is the reason why all of hackers are using __C__ or __C++__ language for their __hack stuff__ in target systems and python or bash for their __automation stuff__ in their own system.
In my experience, __C++__ is good and fast enough for hack stuff but of course if you are gonna deep in this subject, you need to start coding in __C__ sooner or later.
## Suggestion 3
At least use a license for your codes, cause everyone can now copy your code with no permissions and claim that he/she is the author of it, not you.
Best regards,

Mahmood Heidari

**Comment by RyanNorooz** [comment]
Hey there, Thanks for the Tips!

I purposefully did not include the compiled exe file cuz no one trusts executables from a stranger.
feel free to use the code for your own needs which I'm definitely not gonna be related to😊

I know python isn't the best tool for hacking stuff but also running some console commands isn't necessarily hacking tho!
I'd call it automation at best🤷‍♂️
also I'm starting some private projects which will most definitely be needing C or C++ for some processing parts, so thats coming to my tech stack too😌


License? come on bro...!
that would mean that I would have to check is someone else had built such thing and I didn't have the energy for that kinda thing
